package com.kafka.entity;
// Generated May 3, 2019 5:38:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="dbsistemakademik"
)
public class Account  implements java.io.Serializable {


     private Integer idaccount;
     private Jabatan jabatan;
     private String usernameAccount;
     private String password;
     private String emailAccount;
     private String telpAccount;
     private String namaDepanAccount;
     private String namaBelakangAccount;

    public Account() {
    }

	
    public Account(Jabatan jabatan, String usernameAccount, String password, String emailAccount, String telpAccount, String namaDepanAccount) {
        this.jabatan = jabatan;
        this.usernameAccount = usernameAccount;
        this.password = password;
        this.emailAccount = emailAccount;
        this.telpAccount = telpAccount;
        this.namaDepanAccount = namaDepanAccount;
    }
    public Account(Jabatan jabatan, String usernameAccount, String password, String emailAccount, String telpAccount, String namaDepanAccount, String namaBelakangAccount) {
       this.jabatan = jabatan;
       this.usernameAccount = usernameAccount;
       this.password = password;
       this.emailAccount = emailAccount;
       this.telpAccount = telpAccount;
       this.namaDepanAccount = namaDepanAccount;
       this.namaBelakangAccount = namaBelakangAccount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDAccount", unique=true, nullable=false)
    public Integer getIdaccount() {
        return this.idaccount;
    }
    
    public void setIdaccount(Integer idaccount) {
        this.idaccount = idaccount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Jabatan_IDJabatan", nullable=false)
    public Jabatan getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(Jabatan jabatan) {
        this.jabatan = jabatan;
    }

    
    @Column(name="UsernameAccount", nullable=false, length=30)
    public String getUsernameAccount() {
        return this.usernameAccount;
    }
    
    public void setUsernameAccount(String usernameAccount) {
        this.usernameAccount = usernameAccount;
    }

    
    @Column(name="Password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="EmailAccount", nullable=false, length=60)
    public String getEmailAccount() {
        return this.emailAccount;
    }
    
    public void setEmailAccount(String emailAccount) {
        this.emailAccount = emailAccount;
    }

    
    @Column(name="TelpAccount", nullable=false, length=12)
    public String getTelpAccount() {
        return this.telpAccount;
    }
    
    public void setTelpAccount(String telpAccount) {
        this.telpAccount = telpAccount;
    }

    
    @Column(name="NamaDepanAccount", nullable=false, length=60)
    public String getNamaDepanAccount() {
        return this.namaDepanAccount;
    }
    
    public void setNamaDepanAccount(String namaDepanAccount) {
        this.namaDepanAccount = namaDepanAccount;
    }

    
    @Column(name="NamaBelakangAccount", length=60)
    public String getNamaBelakangAccount() {
        return this.namaBelakangAccount;
    }
    
    public void setNamaBelakangAccount(String namaBelakangAccount) {
        this.namaBelakangAccount = namaBelakangAccount;
    }




}


