package com.kafka.entity;
// Generated May 5, 2019 2:37:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Dosen generated by hbm2java
 */
@Entity
@Table(name="dosen"
    ,catalog="dbsistemakademik"
    , uniqueConstraints = @UniqueConstraint(columnNames="NIDNDosen") 
)
public class Dosen  implements java.io.Serializable {


     private String nikdosen;
     private String nidndosen;
     private String namaDepanDosen;
     private String namaBelakangDosen;
     private String gelarDepanDosen;
     private String gelarBelakangDosen;
     private byte[] imageDosen;
     private Set<Mahasiswa> mahasiswas = new HashSet<Mahasiswa>(0);
     private Set<Jadwalkelas> jadwalkelases = new HashSet<Jadwalkelas>(0);

    public Dosen() {
    }

	
    public Dosen(String nikdosen, String nidndosen) {
        this.nikdosen = nikdosen;
        this.nidndosen = nidndosen;
    }
    public Dosen(String nikdosen, String nidndosen, String namaDepanDosen, String namaBelakangDosen, String gelarDepanDosen, String gelarBelakangDosen, byte[] imageDosen, Set<Mahasiswa> mahasiswas, Set<Jadwalkelas> jadwalkelases) {
       this.nikdosen = nikdosen;
       this.nidndosen = nidndosen;
       this.namaDepanDosen = namaDepanDosen;
       this.namaBelakangDosen = namaBelakangDosen;
       this.gelarDepanDosen = gelarDepanDosen;
       this.gelarBelakangDosen = gelarBelakangDosen;
       this.imageDosen = imageDosen;
       this.mahasiswas = mahasiswas;
       this.jadwalkelases = jadwalkelases;
    }
   
     @Id 

    
    @Column(name="NIKDosen", unique=true, nullable=false, length=16)
    public String getNikdosen() {
        return this.nikdosen;
    }
    
    public void setNikdosen(String nikdosen) {
        this.nikdosen = nikdosen;
    }

    
    @Column(name="NIDNDosen", unique=true, nullable=false, length=10)
    public String getNidndosen() {
        return this.nidndosen;
    }
    
    public void setNidndosen(String nidndosen) {
        this.nidndosen = nidndosen;
    }

    
    @Column(name="NamaDepanDosen", length=60)
    public String getNamaDepanDosen() {
        return this.namaDepanDosen;
    }
    
    public void setNamaDepanDosen(String namaDepanDosen) {
        this.namaDepanDosen = namaDepanDosen;
    }

    
    @Column(name="NamaBelakangDosen", length=60)
    public String getNamaBelakangDosen() {
        return this.namaBelakangDosen;
    }
    
    public void setNamaBelakangDosen(String namaBelakangDosen) {
        this.namaBelakangDosen = namaBelakangDosen;
    }

    
    @Column(name="GelarDepanDosen", length=60)
    public String getGelarDepanDosen() {
        return this.gelarDepanDosen;
    }
    
    public void setGelarDepanDosen(String gelarDepanDosen) {
        this.gelarDepanDosen = gelarDepanDosen;
    }

    
    @Column(name="GelarBelakangDosen", length=60)
    public String getGelarBelakangDosen() {
        return this.gelarBelakangDosen;
    }
    
    public void setGelarBelakangDosen(String gelarBelakangDosen) {
        this.gelarBelakangDosen = gelarBelakangDosen;
    }

    
    @Column(name="ImageDosen")
    public byte[] getImageDosen() {
        return this.imageDosen;
    }
    
    public void setImageDosen(byte[] imageDosen) {
        this.imageDosen = imageDosen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dosen")
    public Set<Mahasiswa> getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set<Mahasiswa> mahasiswas) {
        this.mahasiswas = mahasiswas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dosen")
    public Set<Jadwalkelas> getJadwalkelases() {
        return this.jadwalkelases;
    }
    
    public void setJadwalkelases(Set<Jadwalkelas> jadwalkelases) {
        this.jadwalkelases = jadwalkelases;
    }




}


