package com.kafka.entity;
// Generated May 3, 2019 5:38:29 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kurikulum generated by hbm2java
 */
@Entity
@Table(name = "kurikulum",
        catalog = "dbsistemakademik"
)
public class Kurikulum implements java.io.Serializable {

    private Integer idkurikulum;
    private String namaKurikulum;
    private boolean statusAktifKurikulum;
    private Set<Matakuliah> matakuliahs = new HashSet<Matakuliah>(0);

    public Kurikulum() {
    }

    public Kurikulum(String namaKurikulum, boolean statusAktifKurikulum,
            Set<Matakuliah> matakuliahs) {
        this.namaKurikulum = namaKurikulum;
        this.statusAktifKurikulum = statusAktifKurikulum;
        this.matakuliahs = matakuliahs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "IDKurikulum", unique = true, nullable = false)
    public Integer getIdkurikulum() {
        return this.idkurikulum;
    }

    public void setIdkurikulum(Integer idkurikulum) {
        this.idkurikulum = idkurikulum;
    }

    @Column(name = "NamaKurikulum", length = 45)
    public String getNamaKurikulum() {
        return this.namaKurikulum;
    }

    public void setNamaKurikulum(String namaKurikulum) {
        this.namaKurikulum = namaKurikulum;
    }

    @Column(name = "StatusAktifKurikulum")
    public boolean getStatusAktifKurikulum() {
        return this.statusAktifKurikulum;
    }

    public void setStatusAktifKurikulum(boolean statusAktifKurikulum) {
        this.statusAktifKurikulum = statusAktifKurikulum;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "kurikulum")
    public Set<Matakuliah> getMatakuliahs() {
        return this.matakuliahs;
    }

    public void setMatakuliahs(Set<Matakuliah> matakuliahs) {
        this.matakuliahs = matakuliahs;
    }

    @Override
    public String toString() {
        return this.namaKurikulum;
    }

}
