package com.kafka.entity;
// Generated May 3, 2019 5:38:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matakuliah generated by hbm2java
 */
@Entity
@Table(name="matakuliah"
    ,catalog="dbsistemakademik"
)
public class Matakuliah  implements java.io.Serializable {


     private String kodeMataKuliah;
     private Kurikulum kurikulum;
     private String namaMataKuliah;
     private int sksteoriMataKuliah;
     private int skspraktikumMataKuliah;
     private String deskripsiMataKuliah;
     private Set<Jadwalkelas> jadwalkelases = new HashSet<Jadwalkelas>(0);
     private Set<Nilai> nilais = new HashSet<Nilai>(0);

    public Matakuliah() {
    }

	
    public Matakuliah(String kodeMataKuliah, Kurikulum kurikulum, String namaMataKuliah, int sksteoriMataKuliah, int skspraktikumMataKuliah, String deskripsiMataKuliah) {
        this.kodeMataKuliah = kodeMataKuliah;
        this.kurikulum = kurikulum;
        this.namaMataKuliah = namaMataKuliah;
        this.sksteoriMataKuliah = sksteoriMataKuliah;
        this.skspraktikumMataKuliah = skspraktikumMataKuliah;
        this.deskripsiMataKuliah = deskripsiMataKuliah;
    }
    public Matakuliah(String kodeMataKuliah, Kurikulum kurikulum, String namaMataKuliah, int sksteoriMataKuliah, int skspraktikumMataKuliah, String deskripsiMataKuliah, Set<Jadwalkelas> jadwalkelases, Set<Nilai> nilais) {
       this.kodeMataKuliah = kodeMataKuliah;
       this.kurikulum = kurikulum;
       this.namaMataKuliah = namaMataKuliah;
       this.sksteoriMataKuliah = sksteoriMataKuliah;
       this.skspraktikumMataKuliah = skspraktikumMataKuliah;
       this.deskripsiMataKuliah = deskripsiMataKuliah;
       this.jadwalkelases = jadwalkelases;
       this.nilais = nilais;
    }
   
     @Id 

    
    @Column(name="KodeMataKuliah", unique=true, nullable=false, length=5)
    public String getKodeMataKuliah() {
        return this.kodeMataKuliah;
    }
    
    public void setKodeMataKuliah(String kodeMataKuliah) {
        this.kodeMataKuliah = kodeMataKuliah;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Kurikulum_IDKurikulum", nullable=false)
    public Kurikulum getKurikulum() {
        return this.kurikulum;
    }
    
    public void setKurikulum(Kurikulum kurikulum) {
        this.kurikulum = kurikulum;
    }

    
    @Column(name="NamaMataKuliah", nullable=false, length=60)
    public String getNamaMataKuliah() {
        return this.namaMataKuliah;
    }
    
    public void setNamaMataKuliah(String namaMataKuliah) {
        this.namaMataKuliah = namaMataKuliah;
    }

    
    @Column(name="SKSTeoriMataKuliah", nullable=false)
    public int getSksteoriMataKuliah() {
        return this.sksteoriMataKuliah;
    }
    
    public void setSksteoriMataKuliah(int sksteoriMataKuliah) {
        this.sksteoriMataKuliah = sksteoriMataKuliah;
    }

    
    @Column(name="SKSPraktikumMataKuliah", nullable=false)
    public int getSkspraktikumMataKuliah() {
        return this.skspraktikumMataKuliah;
    }
    
    public void setSkspraktikumMataKuliah(int skspraktikumMataKuliah) {
        this.skspraktikumMataKuliah = skspraktikumMataKuliah;
    }

    
    @Column(name="DeskripsiMataKuliah", nullable=false, length=1000)
    public String getDeskripsiMataKuliah() {
        return this.deskripsiMataKuliah;
    }
    
    public void setDeskripsiMataKuliah(String deskripsiMataKuliah) {
        this.deskripsiMataKuliah = deskripsiMataKuliah;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matakuliah")
    public Set<Jadwalkelas> getJadwalkelases() {
        return this.jadwalkelases;
    }
    
    public void setJadwalkelases(Set<Jadwalkelas> jadwalkelases) {
        this.jadwalkelases = jadwalkelases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matakuliah")
    public Set<Nilai> getNilais() {
        return this.nilais;
    }
    
    public void setNilais(Set<Nilai> nilais) {
        this.nilais = nilais;
    }




}


