package com.kafka.entity;
// Generated May 5, 2019 2:37:27 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Nilai generated by hbm2java
 */
@Entity
@Table(name="nilai"
    ,catalog="dbsistemakademik"
    , uniqueConstraints = @UniqueConstraint(columnNames="IDNilai") 
)
public class Nilai  implements java.io.Serializable {


     private NilaiId id;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;
     private Double utsnilai;
     private Double uasnilai;
     private Double katnilai;

    public Nilai() {
    }

	
    public Nilai(NilaiId id, Mahasiswa mahasiswa, Matakuliah matakuliah) {
        this.id = id;
        this.mahasiswa = mahasiswa;
        this.matakuliah = matakuliah;
    }
    public Nilai(NilaiId id, Mahasiswa mahasiswa, Matakuliah matakuliah, Double utsnilai, Double uasnilai, Double katnilai) {
       this.id = id;
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
       this.utsnilai = utsnilai;
       this.uasnilai = uasnilai;
       this.katnilai = katnilai;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idnilai", column=@Column(name="IDNilai", unique=true, nullable=false) ), 
        @AttributeOverride(name="mataKuliahKodeMataKuliah", column=@Column(name="MataKuliah_KodeMataKuliah", nullable=false, length=5) ) } )
    public NilaiId getId() {
        return this.id;
    }
    
    public void setId(NilaiId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Mahasiswa_NRPMahasiswa", nullable=false)
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MataKuliah_KodeMataKuliah", nullable=false, insertable=false, updatable=false)
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }

    
    @Column(name="UTSNilai", precision=22, scale=0)
    public Double getUtsnilai() {
        return this.utsnilai;
    }
    
    public void setUtsnilai(Double utsnilai) {
        this.utsnilai = utsnilai;
    }

    
    @Column(name="UASNilai", precision=22, scale=0)
    public Double getUasnilai() {
        return this.uasnilai;
    }
    
    public void setUasnilai(Double uasnilai) {
        this.uasnilai = uasnilai;
    }

    
    @Column(name="KATNilai", precision=22, scale=0)
    public Double getKatnilai() {
        return this.katnilai;
    }
    
    public void setKatnilai(Double katnilai) {
        this.katnilai = katnilai;
    }




}


