package com.kafka.entity;
// Generated Apr 20, 2019 10:10:57 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Nilai generated by hbm2java
 */
@Entity
@Table(name="nilai"
    ,catalog="dbsistemakademik"
)
public class Nilai  implements java.io.Serializable {


     private Integer idnilai;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;
     private Double utsnilai;
     private Double uasnilai;
     private Double katnilai;

    public Nilai() {
    }

	
    public Nilai(Mahasiswa mahasiswa, Matakuliah matakuliah) {
        this.mahasiswa = mahasiswa;
        this.matakuliah = matakuliah;
    }
    public Nilai(Mahasiswa mahasiswa, Matakuliah matakuliah, Double utsnilai, Double uasnilai, Double katnilai) {
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
       this.utsnilai = utsnilai;
       this.uasnilai = uasnilai;
       this.katnilai = katnilai;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDNilai", unique=true, nullable=false)
    public Integer getIdnilai() {
        return this.idnilai;
    }
    
    public void setIdnilai(Integer idnilai) {
        this.idnilai = idnilai;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Mahasiswa_NRPMahasiswa", nullable=false)
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MataKuliah_KodeMataKuliah", nullable=false)
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }

    
    @Column(name="UTSNilai", precision=22, scale=0)
    public Double getUtsnilai() {
        return this.utsnilai;
    }
    
    public void setUtsnilai(Double utsnilai) {
        this.utsnilai = utsnilai;
    }

    
    @Column(name="UASNilai", precision=22, scale=0)
    public Double getUasnilai() {
        return this.uasnilai;
    }
    
    public void setUasnilai(Double uasnilai) {
        this.uasnilai = uasnilai;
    }

    
    @Column(name="KATNilai", precision=22, scale=0)
    public Double getKatnilai() {
        return this.katnilai;
    }
    
    public void setKatnilai(Double katnilai) {
        this.katnilai = katnilai;
    }




}


