package com.kafka.entity;
// Generated May 3, 2019 5:38:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WisudaId generated by hbm2java
 */
@Embeddable
public class WisudaId  implements java.io.Serializable {


     private String periodeWisuda;
     private String mahasiswaNrpmahasiswa;

    public WisudaId() {
    }

    public WisudaId(String periodeWisuda, String mahasiswaNrpmahasiswa) {
       this.periodeWisuda = periodeWisuda;
       this.mahasiswaNrpmahasiswa = mahasiswaNrpmahasiswa;
    }
   


    @Column(name="PeriodeWisuda", nullable=false, length=9)
    public String getPeriodeWisuda() {
        return this.periodeWisuda;
    }
    
    public void setPeriodeWisuda(String periodeWisuda) {
        this.periodeWisuda = periodeWisuda;
    }


    @Column(name="Mahasiswa_NRPMahasiswa", nullable=false, length=7)
    public String getMahasiswaNrpmahasiswa() {
        return this.mahasiswaNrpmahasiswa;
    }
    
    public void setMahasiswaNrpmahasiswa(String mahasiswaNrpmahasiswa) {
        this.mahasiswaNrpmahasiswa = mahasiswaNrpmahasiswa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WisudaId) ) return false;
		 WisudaId castOther = ( WisudaId ) other; 
         
		 return ( (this.getPeriodeWisuda()==castOther.getPeriodeWisuda()) || ( this.getPeriodeWisuda()!=null && castOther.getPeriodeWisuda()!=null && this.getPeriodeWisuda().equals(castOther.getPeriodeWisuda()) ) )
 && ( (this.getMahasiswaNrpmahasiswa()==castOther.getMahasiswaNrpmahasiswa()) || ( this.getMahasiswaNrpmahasiswa()!=null && castOther.getMahasiswaNrpmahasiswa()!=null && this.getMahasiswaNrpmahasiswa().equals(castOther.getMahasiswaNrpmahasiswa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPeriodeWisuda() == null ? 0 : this.getPeriodeWisuda().hashCode() );
         result = 37 * result + ( getMahasiswaNrpmahasiswa() == null ? 0 : this.getMahasiswaNrpmahasiswa().hashCode() );
         return result;
   }   


}


