package com.kafka.entity;
// Generated May 5, 2019 2:37:27 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wisuda generated by hbm2java
 */
@Entity
@Table(name="wisuda"
    ,catalog="dbsistemakademik"
)
public class Wisuda  implements java.io.Serializable {


     private WisudaId id;
     private Mahasiswa mahasiswa;
     private String judulTainggrisWisuda;
     private String judulTaindonesiaWisuda;
     private Byte statusCekalWisuda;

    public Wisuda() {
    }

	
    public Wisuda(WisudaId id, Mahasiswa mahasiswa) {
        this.id = id;
        this.mahasiswa = mahasiswa;
    }
    public Wisuda(WisudaId id, Mahasiswa mahasiswa, String judulTainggrisWisuda, String judulTaindonesiaWisuda, Byte statusCekalWisuda) {
       this.id = id;
       this.mahasiswa = mahasiswa;
       this.judulTainggrisWisuda = judulTainggrisWisuda;
       this.judulTaindonesiaWisuda = judulTaindonesiaWisuda;
       this.statusCekalWisuda = statusCekalWisuda;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="periodeWisuda", column=@Column(name="PeriodeWisuda", nullable=false, length=9) ), 
        @AttributeOverride(name="mahasiswaNrpmahasiswa", column=@Column(name="Mahasiswa_NRPMahasiswa", nullable=false, length=7) ) } )
    public WisudaId getId() {
        return this.id;
    }
    
    public void setId(WisudaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Mahasiswa_NRPMahasiswa", nullable=false, insertable=false, updatable=false)
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }

    
    @Column(name="JudulTAInggrisWisuda", length=250)
    public String getJudulTainggrisWisuda() {
        return this.judulTainggrisWisuda;
    }
    
    public void setJudulTainggrisWisuda(String judulTainggrisWisuda) {
        this.judulTainggrisWisuda = judulTainggrisWisuda;
    }

    
    @Column(name="JudulTAIndonesiaWisuda", length=250)
    public String getJudulTaindonesiaWisuda() {
        return this.judulTaindonesiaWisuda;
    }
    
    public void setJudulTaindonesiaWisuda(String judulTaindonesiaWisuda) {
        this.judulTaindonesiaWisuda = judulTaindonesiaWisuda;
    }

    
    @Column(name="StatusCekalWisuda")
    public Byte getStatusCekalWisuda() {
        return this.statusCekalWisuda;
    }
    
    public void setStatusCekalWisuda(Byte statusCekalWisuda) {
        this.statusCekalWisuda = statusCekalWisuda;
    }




}


